build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - ./scripts/ci.sh levmar
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: levmar
    source: deploy/
    target: ~
    recursive: true
    delete: false
